name: CI

on:
  push:
    branches: [ main, release-* ]
  pull_request:
    branches: [ main, release-* ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: ci
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run Go build and test
      run: |
        go build -v ./...
        echo "✅ Go build completed successfully"
    
    - name: Run calculator demo
      run: |
        go run .
        echo "✅ Calculator demo completed successfully"
    
    - name: Validate Mergify config
      run: |
        # Simple validation that .mergify.yml exists and is not empty
        if [ -f ".mergify.yml" ] && [ -s ".mergify.yml" ]; then
          echo "✅ Mergify configuration found"
        else
          echo "❌ Mergify configuration missing or empty"
          exit 1
        fi
    
    - name: Check documentation
      run: |
        if [ -f "README.md" ] && grep -q "mergify" "README.md"; then
          echo "✅ Documentation includes Mergify information"
        else
          echo "❌ Documentation missing Mergify information"
          exit 1
        fi